CREATE TABLE IF NOT EXISTS projects (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  image TEXT,
  category TEXT NOT NULL,
  is_long_image BOOLEAN DEFAULT FALSE,
  tech JSONB DEFAULT '[]'::jsonb,
  live_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

-- Remove existing policies (if any)
DROP POLICY IF EXISTS "allow_all_operations" ON "public"."projects";

-- Create a policy to allow all operations
CREATE POLICY "allow_all_operations"
ON "public"."projects"
AS PERMISSIVE FOR ALL
TO public
USING (true)
WITH CHECK (true);

-- Create storage bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('project-images', 'project-images', true)
ON CONFLICT (id) DO NOTHING;

-- Remove existing storage policies (if any)
DROP POLICY IF EXISTS "allow_public_read" ON storage.objects;
DROP POLICY IF EXISTS "allow_public_upload" ON storage.objects;

-- Create storage policies
CREATE POLICY "allow_public_read"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'project-images');

CREATE POLICY "allow_public_upload"
ON storage.objects FOR INSERT
TO public
WITH CHECK (bucket_id = 'project-images');

-- Projects table (you might already have this)
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  image TEXT,
  category TEXT,
  tech TEXT[],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Page views table
CREATE TABLE IF NOT EXISTS page_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_path TEXT NOT NULL,
  viewed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  visitor_id TEXT -- You can use this to track unique visitors (can be anonymous)
);

-- Function to get total projects
CREATE OR REPLACE FUNCTION get_total_projects()
RETURNS TABLE (
  total_count BIGINT,
  monthly_change BIGINT
) 
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    COUNT(*)::BIGINT as total_count,
    COUNT(*) FILTER (WHERE created_at >= date_trunc('month', NOW()))::BIGINT as monthly_change
  FROM projects;
END;
$$;

-- Function to get daily views
CREATE OR REPLACE FUNCTION get_daily_views()
RETURNS TABLE (
  today_count BIGINT,
  yesterday_count BIGINT
) 
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    COUNT(*) FILTER (WHERE viewed_at::date = CURRENT_DATE)::BIGINT as today_count,
    COUNT(*) FILTER (WHERE viewed_at::date = CURRENT_DATE - 1)::BIGINT as yesterday_count
  FROM page_views;
END;
$$;

-- Function to get monthly views
CREATE OR REPLACE FUNCTION get_monthly_views()
RETURNS TABLE (
  current_month_count BIGINT,
  last_month_count BIGINT
) 
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    COUNT(*) FILTER (WHERE viewed_at >= date_trunc('month', NOW()))::BIGINT as current_month_count,
    COUNT(*) FILTER (
      WHERE viewed_at >= date_trunc('month', NOW() - interval '1 month') 
      AND viewed_at < date_trunc('month', NOW())
    )::BIGINT as last_month_count
  FROM page_views;
END;
$$;

-- Create availability settings table
CREATE TABLE IF NOT EXISTS availability_settings (
  id SERIAL PRIMARY KEY,
  is_available BOOLEAN DEFAULT true,
  message TEXT DEFAULT 'Available for new projects',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default settings
INSERT INTO availability_settings (is_available, message)
VALUES (true, 'Available for new projects')
ON CONFLICT DO NOTHING;

-- First, drop the existing trigger if it exists
DROP TRIGGER IF EXISTS update_hero_settings_updated_at ON public.hero_settings;

-- Create or replace the trigger function (only define this once)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create hero_settings table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.hero_settings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'busy', 'offline')),
    available_text TEXT NOT NULL DEFAULT 'I''m available for new projects',
    busy_text TEXT NOT NULL DEFAULT 'I''m really busy right now',
    offline_text TEXT NOT NULL DEFAULT 'I''m currently offline',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create the trigger
CREATE TRIGGER update_hero_settings_updated_at
    BEFORE UPDATE ON public.hero_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Insert default row if not exists
INSERT INTO public.hero_settings (id, status, available_text, busy_text, offline_text)
VALUES ('00000000-0000-0000-0000-000000000000', 'available', 'I''m available for new projects', 'I''m really busy right now', 'I''m currently offline')
ON CONFLICT (id) DO NOTHING;

-- First, drop the table if it exists to start fresh
DROP TABLE IF EXISTS public.about_settings;

-- Create the table
CREATE TABLE public.about_settings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT[] NOT NULL,
    image_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default data
INSERT INTO public.about_settings (title, description, image_url)
VALUES (
    'Crafting Digital Experiences with Modern Web Technologies',
    ARRAY[
        'Hello! I''m [Your Name], a Full Stack Web Developer passionate about creating innovative digital solutions. With expertise in React, Next.js, Laravel, and Node.js, I specialize in building scalable and user-friendly web applications.',
        'My approach combines clean code practices with modern development tools to deliver high-quality solutions. I focus on creating seamless user experiences while ensuring robust and efficient server-side operations.',
        'When I''m not coding, I''m constantly exploring new technologies and best practices to stay at the forefront of web development. I believe in writing clean, maintainable code and creating applications that make a difference.'
    ],
    '/your-image.jpg'
);

-- Create the trigger for about_settings (using a different trigger name)
DROP TRIGGER IF EXISTS update_about_settings_updated_at ON public.about_settings;
CREATE TRIGGER update_about_settings_updated_at
    BEFORE UPDATE ON public.about_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Create contact_settings table
CREATE TABLE IF NOT EXISTS contact_settings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL DEFAULT 'Let''s Connect',
    description TEXT NOT NULL DEFAULT 'Feel free to reach out through any of these channels',
    email TEXT NOT NULL DEFAULT 'your.email@example.com',
    phone TEXT NOT NULL DEFAULT '+1 234 567 890',
    location TEXT NOT NULL DEFAULT 'Your Location, Country',
    social_links JSONB NOT NULL DEFAULT '{
        "github": "https://github.com/yourusername",
        "linkedin": "https://linkedin.com/in/yourusername",
        "twitter": "https://twitter.com/yourusername",
        "facebook": "https://facebook.com/yourusername"
    }'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Drop the trigger if it exists before creating it
DROP TRIGGER IF EXISTS update_contact_settings_updated_at ON contact_settings;
CREATE TRIGGER update_contact_settings_updated_at
    BEFORE UPDATE ON contact_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Insert default row if not exists
INSERT INTO contact_settings (id)
SELECT gen_random_uuid()
WHERE NOT EXISTS (SELECT 1 FROM contact_settings); 

-- Create a table to track pings to keep the Supabase instance active
CREATE TABLE IF NOT EXISTS _pings (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add an initial record
INSERT INTO _pings (created_at) VALUES (NOW());

-- Create an index on created_at for faster queries
CREATE INDEX IF NOT EXISTS idx_pings_created_at ON _pings (created_at);

-- Create a function to clean up old ping records (keep only the last 100)
CREATE OR REPLACE FUNCTION cleanup_pings()
RETURNS TRIGGER AS $$
BEGIN
  DELETE FROM _pings
  WHERE id NOT IN (
    SELECT id FROM _pings
    ORDER BY created_at DESC
    LIMIT 100
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create a trigger to run the cleanup function after each insert
DROP TRIGGER IF EXISTS trigger_cleanup_pings ON _pings;
CREATE TRIGGER trigger_cleanup_pings
AFTER INSERT ON _pings
EXECUTE FUNCTION cleanup_pings(); 